// store/counterSlice.js
import {createSlice} from "@reduxjs/toolkit";

// Create a slice for the counter
export const sharingSlice = createSlice({
  name: 'sharing',
  initialState: {
    items: [],
  },
  reducers: {
    push: (state, action) => {
        state.items.push(action.payload); // Add a string to the array
    },
    pull: (state, action) => {
      const index = state.items.indexOf(action.payload);
      if (index > -1) {
        state.items.splice(index, 1); // Remove the specified string
      }
    },
    empty : (state) => {
      state.items = [];
    }
  }
});

// Export the actions generated by the slice
export const { push, pull, empty } = sharingSlice.actions;

// Export the reducer to be used in the store
export default sharingSlice.reducer;